SECRET_KEY = 'your_secret_key'
GOOGLE_CLIENT_ID = 'your_google_client_id'
GOOGLE_CLIENT_SECRET = 'your_google_client_secret'
GOOGLE_REDIRECT_URI = 'your_google_redirect_uri'
ZOOM_CLIENT_ID = 'your_zoom_client_id'
ZOOM_CLIENT_SECRET = 'your_zoom_client_secret'
ZOOM_REDIRECT_URI = 'your_zoom_redirect_uri'